package net.it_tim.dude_of_dude.db_classes;

// Generated 14 квіт 2011 15:28:49 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Groups generated by hbm2java
 */
public class Groups implements java.io.Serializable {

	private int groupId;
	private String description;
	private Set<Contacts> contactses = new HashSet<Contacts>(0);
	private Set<Hosts> hostses = new HashSet<Hosts>(0);

	public Groups() {
	}

	public Groups(int groupId) {
		this.groupId = groupId;
	}

	public Groups(int groupId, String description, Set<Contacts> contactses,
			Set<Hosts> hostses) {
		this.groupId = groupId;
		this.description = description;
		this.contactses = contactses;
		this.hostses = hostses;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Contacts> getContactses() {
		return this.contactses;
	}

	public void setContactses(Set<Contacts> contactses) {
		this.contactses = contactses;
	}

	public Set<Hosts> getHostses() {
		return this.hostses;
	}

	public void setHostses(Set<Hosts> hostses) {
		this.hostses = hostses;
	}

}
