package net.it_tim.dude_of_dude.db_classes;

// Generated 14 квіт 2011 15:28:49 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Hosts generated by hbm2java
 */
public class Hosts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int hostId;
	private String ipAdres;
	private String description;
	private Long timeoutMs;
	private Long intervalMs;
	private Boolean toPing;
	private NotificatioinsHistory notificatioinsHistory;
	private Set<Groups> groupses = new HashSet<Groups>(0);
	private PingHistory pingHistory;

	public Hosts() {
	}

	public Hosts(int hostId) {
		this.hostId = hostId;
	}

	public Hosts(int hostId, String ipAdres, String description,
			Long timeoutMs, Long intervalMs, Boolean toPing,
			NotificatioinsHistory notificatioinsHistory, Set<Groups> groupses,
			PingHistory pingHistory) {
		this.hostId = hostId;
		this.ipAdres = ipAdres;
		this.description = description;
		this.timeoutMs = timeoutMs;
		this.intervalMs = intervalMs;
		this.toPing = toPing;
		this.notificatioinsHistory = notificatioinsHistory;
		this.groupses = groupses;
		this.pingHistory = pingHistory;
	}

	public int getHostId() {
		return this.hostId;
	}

	public void setHostId(int hostId) {
		this.hostId = hostId;
	}

	public String getIpAdres() {
		return this.ipAdres;
	}

	public void setIpAdres(String ipAdres) {
		this.ipAdres = ipAdres;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Long getTimeoutMs() {
		return this.timeoutMs;
	}

	public void setTimeoutMs(Long timeoutMs) {
		this.timeoutMs = timeoutMs;
	}

	public Long getIntervalMs() {
		return this.intervalMs;
	}

	public void setIntervalMs(Long intervalMs) {
		this.intervalMs = intervalMs;
	}

	public Boolean getToPing() {
		return this.toPing;
	}

	public void setToPing(Boolean toPing) {
		this.toPing = toPing;
	}

	public NotificatioinsHistory getNotificatioinsHistory() {
		return this.notificatioinsHistory;
	}

	public void setNotificatioinsHistory(
			NotificatioinsHistory notificatioinsHistory) {
		this.notificatioinsHistory = notificatioinsHistory;
	}

	public Set<Groups> getGroupses() {
		return this.groupses;
	}

	public void setGroupses(Set<Groups> groupses) {
		this.groupses = groupses;
	}

	public PingHistory getPingHistory() {
		return this.pingHistory;
	}

	public void setPingHistory(PingHistory pingHistory) {
		this.pingHistory = pingHistory;
	}

}
