package net.it_tim.dude_of_dude.db_classes;

// Generated 14 квіт 2011 15:28:49 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * PingHistory generated by hbm2java
 */
public class PingHistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int hostId;
	private Hosts hosts;
	private Date stamp;
	private Boolean status;
	private Integer timeout;

	public PingHistory() {
	}

	public PingHistory(Hosts hosts) {
		this.hosts = hosts;
	}

	public PingHistory(Hosts hosts, Date stamp, Boolean status, Integer timeout) {
		this.hosts = hosts;
		this.stamp = stamp;
		this.status = status;
		this.timeout = timeout;
	}

	public int getHostId() {
		return this.hostId;
	}

	public void setHostId(int hostId) {
		this.hostId = hostId;
	}

	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	public Date getStamp() {
		return this.stamp;
	}

	public void setStamp(Date stamp) {
		this.stamp = stamp;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Integer getTimeout() {
		return this.timeout;
	}

	public void setTimeout(Integer timeout) {
		this.timeout = timeout;
	}

}
