package net.it_tim.dude_of_dude.database;

// Generated 20 квіт 2011 10:24:30 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Contacts generated by hbm2java
 */
public class Contacts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int contactId;
	private Users users;
	private String contact;
	private Set<Groups> groupses = new HashSet<Groups>(0);

	public Contacts() {
	}

	public Contacts(int contactId) {
		this.contactId = contactId;
	}

	public Contacts(int contactId, Users users, String contact,
			Set<Groups> groupses) {
		this.contactId = contactId;
		this.users = users;
		this.contact = contact;
		this.groupses = groupses;
	}

	public int getContactId() {
		return this.contactId;
	}

	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public Set<Groups> getGroupses() {
		return this.groupses;
	}

	public void setGroupses(Set<Groups> groupses) {
		this.groupses = groupses;
	}

}
