package net.it_tim.dude_of_dude.database;

// Generated 20 квіт 2011 10:24:30 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * NotificatioinsHistory generated by hbm2java
 */
@SuppressWarnings("serial")
public class NotificatioinsHistory implements java.io.Serializable {

	private int id;
	private Hosts hosts;
	private Date stamp;
	private Boolean status;

	public NotificatioinsHistory() {
	}

	public NotificatioinsHistory(int id, Hosts hosts) {
		this.id = id;
		this.hosts = hosts;
	}

	public NotificatioinsHistory(int id, Hosts hosts, Date stamp, Boolean status) {
		this.id = id;
		this.hosts = hosts;
		this.stamp = stamp;
		this.status = status;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	public Date getStamp() {
		return this.stamp;
	}

	public void setStamp(Date stamp) {
		this.stamp = stamp;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
