package net.it_tim.dude_of_dude.database;

// Generated 20 квіт 2011 10:24:30 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * PingHistory generated by hbm2java
 */
public class PingHistory implements java.io.Serializable {

	private int id;
	private Hosts hosts;
	private Date stamp;
	private Boolean status;
	private Integer timeout;

	public PingHistory() {
	}

	public PingHistory(int id, Hosts hosts) {
		this.id = id;
		this.hosts = hosts;
	}

	public PingHistory(int id, Hosts hosts, Date stamp, Boolean status,
			Integer timeout) {
		this.id = id;
		this.hosts = hosts;
		this.stamp = stamp;
		this.status = status;
		this.timeout = timeout;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	public Date getStamp() {
		return this.stamp;
	}

	public void setStamp(Date stamp) {
		this.stamp = stamp;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Integer getTimeout() {
		return this.timeout;
	}

	public void setTimeout(Integer timeout) {
		this.timeout = timeout;
	}

}
